services:
  minha-api:
    container_name: oficina_api_service
    build:
      context: .  # O contexto é a pasta raiz onde está este arquivo.
      dockerfile: ./Dockerfile # O caminho para o Dockerfile a partir da raiz.
    ports:
      # Vamos expor apenas a porta HTTP para facilitar os testes
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=oficina_mecanica_db;Username=oficina_user;Password=1234
    depends_on:
      postgres_db:
        condition: service_healthy # Adicionado para garantir que o banco esteja pronto

  postgres_db:
    image: postgres:16-alpine
    container_name: oficina_mecanica_postgres_db
    environment:
      POSTGRES_DB: oficina_mecanica_db
      POSTGRES_USER: oficina_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficina_user -d oficina_mecanica_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: